// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtk0N7INXSF8KlWfy_S8ur_7CP9WWhRs8',
    appId: '1:307703825406:web:3bff1e2530b3a5b5dbb6af',
    messagingSenderId: '307703825406',
    projectId: 'crypto-list-app-d8c86',
    authDomain: 'crypto-list-app-d8c86.firebaseapp.com',
    storageBucket: 'crypto-list-app-d8c86.appspot.com',
    measurementId: 'G-0NQSK6BN3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNxZQkVE--bhlDB6T0QoNfbMVhzeiN50',
    appId: '1:307703825406:android:255c13deeb36edd9dbb6af',
    messagingSenderId: '307703825406',
    projectId: 'crypto-list-app-d8c86',
    storageBucket: 'crypto-list-app-d8c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0nenoNifJfBeR2v9eJq1HedAWRyfsgDs',
    appId: '1:307703825406:ios:ac044e1b53100846dbb6af',
    messagingSenderId: '307703825406',
    projectId: 'crypto-list-app-d8c86',
    storageBucket: 'crypto-list-app-d8c86.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0nenoNifJfBeR2v9eJq1HedAWRyfsgDs',
    appId: '1:307703825406:ios:ac044e1b53100846dbb6af',
    messagingSenderId: '307703825406',
    projectId: 'crypto-list-app-d8c86',
    storageBucket: 'crypto-list-app-d8c86.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtk0N7INXSF8KlWfy_S8ur_7CP9WWhRs8',
    appId: '1:307703825406:web:ccf588e2da91b465dbb6af',
    messagingSenderId: '307703825406',
    projectId: 'crypto-list-app-d8c86',
    authDomain: 'crypto-list-app-d8c86.firebaseapp.com',
    storageBucket: 'crypto-list-app-d8c86.appspot.com',
    measurementId: 'G-1F3Y73XT81',
  );

}